# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Recipes
author: Wayne Graham
email: wayne.graham@gmail.com
twitter_username: wayne_graham
github_username:  waynegraham
instagram: wsgrah
description: > # this means to ignore newlines until "baseurl:"
  Recipes I've collected and want to be able to find again.
baseurl: "/recipes"
url: "https://waynegraham.github.io"
google_analytics_key:

paginate: 20
paginate_path: "/:num/"
permalink: pretty

# Build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-seo-tag

feed:
  path: atom.xml

collections:
  recipes:
    output: true
    title: recipes
    layout: recipe
    permalink: /recipes/:path/

exclude:
  - gulpfile.js
  - node_modules
  - package.json
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
